version: '2.3'
services:
  fover:
    env_file:
    - .env
    environment:
      FLASK_RUN_HOST: '0.0.0.0'
      FLASK_RUN_PORT: '5000'
    build:
      context: .
      target: release
    ports:
      - 5000:5000
