name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  release:
    types:
    - created

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: fover
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set Docker image tag based on ref
      run: |-
        EVENT="${{ github.event_name }}"

        if [[ "${EVENT}" == "pull_request" ]]; then REF_TAG="${{ github.head_ref }}"
        else REF_TAG_RAW="${{ github.ref }}" REF_TAG="${REF_TAG_RAW##*/}"; fi

        if [[ "${EVENT}" == "push" || "${EVENT}" == "release" ]]; then IMAGE_TAG="${REF_TAG}"
        else IMAGE_TAG="test-${REF_TAG}"; fi

        echo "::set-env name=IMAGE_TAG::${IMAGE_TAG}"
    - name: Build Docker tester and run linting tests
      run: |-
        docker build --target tester -t fover-tester .
        docker run --rm -t -v "$(pwd):/app" fover-tester isort --diff --check-only app.py fover/**/*.py
        docker run --rm -t -v "$(pwd):/app" fover-tester black --check app.py fover/
    - name: Build and push Docker release image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: dsaidgovsg/${{ env.IMAGE_NAME }}
        tags: ${{ env.IMAGE_TAG }}
